// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: trips.proto

package trips

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollabRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CollabRequest) Reset() {
	*x = CollabRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trips_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollabRequest) ProtoMessage() {}

func (x *CollabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trips_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollabRequest.ProtoReflect.Descriptor instead.
func (*CollabRequest) Descriptor() ([]byte, []int) {
	return file_trips_proto_rawDescGZIP(), []int{0}
}

func (x *CollabRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CollabRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollabRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CollabResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Result []byte `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CollabResponse) Reset() {
	*x = CollabResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trips_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollabResponse) ProtoMessage() {}

func (x *CollabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trips_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollabResponse.ProtoReflect.Descriptor instead.
func (*CollabResponse) Descriptor() ([]byte, []int) {
	return file_trips_proto_rawDescGZIP(), []int{1}
}

func (x *CollabResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CollabResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CollabResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollabResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_trips_proto protoreflect.FileDescriptor

var file_trips_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x69, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x72, 0x69, 0x70, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a,
	0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x4d, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x2e,
	0x74, 0x72, 0x69, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6c,
	0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_trips_proto_rawDescOnce sync.Once
	file_trips_proto_rawDescData = file_trips_proto_rawDesc
)

func file_trips_proto_rawDescGZIP() []byte {
	file_trips_proto_rawDescOnce.Do(func() {
		file_trips_proto_rawDescData = protoimpl.X.CompressGZIP(file_trips_proto_rawDescData)
	})
	return file_trips_proto_rawDescData
}

var file_trips_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trips_proto_goTypes = []interface{}{
	(*CollabRequest)(nil),  // 0: trips.CollabRequest
	(*CollabResponse)(nil), // 1: trips.CollabResponse
}
var file_trips_proto_depIdxs = []int32{
	0, // 0: trips.CollabService.Command:input_type -> trips.CollabRequest
	1, // 1: trips.CollabService.Command:output_type -> trips.CollabResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trips_proto_init() }
func file_trips_proto_init() {
	if File_trips_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trips_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollabRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trips_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollabResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trips_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trips_proto_goTypes,
		DependencyIndexes: file_trips_proto_depIdxs,
		MessageInfos:      file_trips_proto_msgTypes,
	}.Build()
	File_trips_proto = out.File
	file_trips_proto_rawDesc = nil
	file_trips_proto_goTypes = nil
	file_trips_proto_depIdxs = nil
}
